#! /usr/bin/env bash
set -e

# Load environment variables from .env if it exists
if [ -f .env ]; then
    echo "Loading configuration from .env..."
    export $(cat .env | grep -v '^#' | xargs)
else
    echo "Warning: .env file not found. Using default values."
    echo "Please copy .env.example to .env and configure it."
    # Set defaults
    export WIFI_SSID="${WIFI_SSID:-default_ssid}"
    export WIFI_PASSWORD="${WIFI_PASSWORD:-default_password}"
    export API_HOST="${API_HOST:-192.168.1.100}"
    export API_PORT="${API_PORT:-8080}"
    export REFRESH_INTERVAL="${REFRESH_INTERVAL:-60}"
fi

# Generate config file from environment variables
echo "Generating configuration..."
cat > internal/config/generated.go <<EOF
// Code generated by build.sh - DO NOT EDIT
// This file is auto-generated from .env during build

package config

// Configuration constants loaded from .env at build time
const (
	WifiSSID        = "$WIFI_SSID"
	WifiPassword    = "$WIFI_PASSWORD"
	APIHost         = "$API_HOST"
	APIPort         = "$API_PORT"
	RefreshInterval = $REFRESH_INTERVAL
)
EOF

echo "✓ Configuration generated"
