{{- if not .Values.secret.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tiny-dash-api.fullname" . }}
  labels:
    {{- include "tiny-dash-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  TINYDASH_HA_TOKEN: {{ required "Either secret.token or secret.existingSecret must be set" .Values.secret.token | quote }}
{{- end -}}
